---
title: "git_01"
author: "Math_116"
date: "Fall semester"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```
# Build a Poem with commits to different branches
Our project will be done using a sequence of save and commits and branch actions.
<!-- Do not modify or change any text in "!--" bracketed areas such as this --- these are instructions to
you, if you change any of this the git program will notice it and compromise your git merging strategy !-->

## First Verse 
<!--Put the first five lines of a poem by Lewis Carrol in this section!-->
In winter, when the fields are white,      
I sing this song for your delight.     
     
In Spring, when woods are getting green,    
I'll try and tell you what I mean.      
     
In Summer, when the days are long,      
Perhaps you'll understand the song.      

## Second Verse
<!--Put the first five lines of a poem by Robert Frost here!-->
Two roads diverged in a yellow wood,  
And sorry I could not travel both   
And be one traveler, long I stood   
And looked down one as far as I could    
To where it bent in the undergrowth;    

## Third Verse
<!--Put the first two verses of The Walrus and the Carpenter here!-->

## Last Verse
<!--Put a short poem of your choice 8-20 lines,here!-->
Isabel met an enormous bear,   
Isabel, Isabel, didn't care;   
The bear was hungry, the bear was ravenous,    
The bear's big mouth was cruel and cavernous.    
The bear said, Isabel, glad to meet you,     
How do, Isabel, now I'll eat you!     
Isabel, Isabel, didn't worry.     
Isabel didn't scream or scurry.    